import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFile } from 'node:child_process';

export function generateHtmlReport(scan) {
  const passRate = scan.passRate ?? 0;
  const violations = scan.violations || [];
  const totalViolations =
    (scan.critical || 0) + (scan.serious || 0) + (scan.moderate || 0) + (scan.minor || 0);

  const url = scan.url || scan.site?.url || 'Unknown';

  const violationRows = violations
    .sort((a, b) => {
      const order = { critical: 0, serious: 1, moderate: 2, minor: 3 };
      return (order[a.impact] ?? 4) - (order[b.impact] ?? 4);
    })
    .map(
      (v) => `
      <tr>
        <td><span class="badge badge-${v.impact || 'minor'}">${(v.impact || 'minor').toUpperCase()}</span></td>
        <td><strong>${escapeHtml(v.id)}</strong></td>
        <td>${escapeHtml(v.description || v.help || '')}</td>
        <td>${v.nodes?.length || 0}</td>
      </tr>`,
    )
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Adibilis Accessibility Report - ${escapeHtml(url)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; padding: 2rem; }
    .container { max-width: 900px; margin: 0 auto; background: #fff; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); overflow: hidden; }
    header { background: #1a1a2e; color: #fff; padding: 2rem; }
    header h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
    header p { opacity: 0.8; font-size: 0.9rem; }
    .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; padding: 2rem; background: #fafafa; }
    .stat { text-align: center; padding: 1rem; border-radius: 8px; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
    .stat .value { font-size: 2rem; font-weight: 700; }
    .stat .label { font-size: 0.8rem; color: #666; margin-top: 0.25rem; }
    .pass-rate { color: ${passRate >= 90 ? '#22c55e' : passRate >= 70 ? '#eab308' : '#ef4444'}; }
    .critical-count { color: #ef4444; }
    .serious-count { color: #f59e0b; }
    .moderate-count { color: #f97316; }
    .minor-count { color: #9ca3af; }
    .violations { padding: 2rem; }
    .violations h2 { margin-bottom: 1rem; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid #eee; }
    th { background: #f9f9f9; font-weight: 600; font-size: 0.85rem; text-transform: uppercase; color: #666; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.7rem; font-weight: 700; color: #fff; }
    .badge-critical { background: #ef4444; }
    .badge-serious { background: #f59e0b; }
    .badge-moderate { background: #f97316; }
    .badge-minor { background: #9ca3af; }
    footer { padding: 1.5rem 2rem; background: #fafafa; text-align: center; font-size: 0.8rem; color: #999; }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>Adibilis Accessibility Report</h1>
      <p>${escapeHtml(url)} &mdash; ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
    </header>
    <div class="summary">
      <div class="stat"><div class="value pass-rate">${passRate}%</div><div class="label">Pass Rate</div></div>
      <div class="stat"><div class="value">${totalViolations}</div><div class="label">Total Violations</div></div>
      <div class="stat"><div class="value critical-count">${scan.critical || 0}</div><div class="label">Critical</div></div>
      <div class="stat"><div class="value serious-count">${scan.serious || 0}</div><div class="label">Serious</div></div>
      <div class="stat"><div class="value moderate-count">${scan.moderate || 0}</div><div class="label">Moderate</div></div>
      <div class="stat"><div class="value minor-count">${scan.minor || 0}</div><div class="label">Minor</div></div>
    </div>
    <div class="violations">
      <h2>Violations</h2>
      <table>
        <thead><tr><th>Severity</th><th>Rule</th><th>Description</th><th>Count</th></tr></thead>
        <tbody>${violationRows || '<tr><td colspan="4" style="text-align:center;padding:2rem;">No violations found</td></tr>'}</tbody>
      </table>
    </div>
    <footer>Generated by Adibilis CLI v1.0.0 &mdash; WCAG 2.2 AA</footer>
  </div>
</body>
</html>`;
}

export async function openReport(scan) {
  const html = generateHtmlReport(scan);
  const tmpFile = path.join(os.tmpdir(), `adibilis-report-${Date.now()}.html`);
  fs.writeFileSync(tmpFile, html, 'utf-8');

  // In headless/CI environments, just return the file path
  if (process.env.CI || !process.stdout.isTTY) {
    return tmpFile;
  }

  const args = process.platform === 'win32' ? ['cmd', ['/c', 'start', '', tmpFile]] : [process.platform === 'darwin' ? 'open' : 'xdg-open', [tmpFile]];

  return new Promise((resolve, reject) => {
    execFile(args[0], args[1], (err) => {
      if (err) reject(err);
      else resolve(tmpFile);
    });
  });
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
